#pragma once
#include "stdafx.h"
#include "xoscStructs.h"

// For ID: 9, V: 2

#define XOSC_FOOTER_MAGIC 0x5F534750

typedef enum _XOSC_FLAGS : QWORD {
	XOSC_FLAGS_TASK_SHOULD_EXIT	= 0x2000000000000000,
	XOSC_FLAGS_TITLE_TERMINATED	= 0x4000000000000000
} XOSC_FLAGS;

typedef enum _SV_PROTECTED_FLAGS {
	FLAG_SV_PROTECTED_NONE = 0x0,
	FLAG_SV_PROTECTED_NO_EJECT_REBOOT = 0x1,
	FLAG_SV_PROTECTED_DISC_AUTHENTICATED = 0x2,
	FLAG_SV_PROTECTED_AUTH_EX_CAPABLE = 0x4
} SV_PROTECTED_FLAGS;

typedef DWORD(*pfnXosc)(VOID* r3, VOID* r4, VOID* r5, RESPONSE_DATA* pBuffer, DWORD respSize);
DWORD CreateXOSCBuffer(VOID* r3, VOID* r4, VOID* r5, RESPONSE_DATA* pBuffer, DWORD respSize);